### ISSUE TITLE
Make test app configurable 

### ISSUE THREAD

**Issue by mastrogiovanni** [italia/spid-express#22]
The spid-express repo contains both Express middleware for Spid ans a simple test application. 
This test application should be customizable: in this way it could also be used as standalone component to orchestrate the SAML conversation as sidecar to a main application.

Endpoints for login, error, acs, IDPs reference, SSH keys and metadata configuration should be runtime configurable using environment variables (user via process.env.XXX).

**Comment by bfabio** [comment]
Implemented in #23
