### ISSUE TITLE
Cannot build package - types error

### ISSUE THREAD

**Issue by valentinoavon** [italia/spid-express#25]
Hi everyone,
I tried to run 

`
npm run build 
`

to build the package dist folder, but I found there are three types errors which make typescript complain.
Could you fix that? We need to manually fix it in order to use the package otherwise.

The errors are in saml.ts and in redis_cache_provider.ts

I guess if it's fixed we could use this package also by using the github reference as dependency instead of downloading it locally.

Thanks!
Valentino

**Comment by bfabio** [comment]
Hi @valentinoavon, can you please add the exact error and node's and npm's versions?

[The Docker image ](https://github.com/italia/spid-express/blob/master/Dockerfile#L21) and the CI pipeline build just fine.

**Comment by valentinoavon** [comment]
Hi @bfabio thanks for the response, what I have is:
node v10.16.0
npm v6.5.0

but it's a problem related to typescript as the errors are wrong types. In fact running npm run build (which executes the typescript compiler) gives the following error:

```
src/strategy/redis_cache_provider.ts:107:32 - error TS2345: Argument of type '(e: Error | null, value?: string | undefined) => void' is not assignable to parameter of type 'Callback<string | null>'.
  Types of parameters 'value' and 'reply' are incompatible.
    Type 'string | null' is not assignable to type 'string | undefined'.
      Type 'null' is not assignable to type 'string | undefined'.

107           redisClient.get(key, callback);
                                   ~~~~~~~~

src/utils/saml.ts:167:25 - error TS2538: Type 'ParsedQs' cannot be used as an index type.

167       fromNullable(idps[entityID]).map(
                            ~~~~~~~~

src/utils/saml.ts:167:25 - error TS2538: Type 'ParsedQs[]' cannot be used as an index type.

167       fromNullable(idps[entityID]).map(
                            ~~~~~~~~

src/utils/saml.ts:167:25 - error TS2538: Type 'string[]' cannot be used as an index type.

167       fromNullable(idps[entityID]).map(
                            ~~~~~~~~

src/utils/saml.ts:221:12 - error TS2345: Argument of type '(authLevel: string) => Option<{ authnContext: string; forceAuthn: boolean; }>' is not assignable to parameter of type '(a: string | string[] | ParsedQs | ParsedQs[]) => Op
tion<{ authnContext: string; forceAuthn: boolean; }>'.
  Types of parameters 'authLevel' and 'a' are incompatible.
    Type 'string | string[] | ParsedQs | ParsedQs[]' is not assignable to type 'string'.
      Type 'string[]' is not assignable to type 'string'.

221     .chain((authLevel: string) =>
               ~~~~~~~~~~~~~~~~~~~~~~
222       lookup(authLevel, SPID_LEVELS)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
232           return none;
    ~~~~~~~~~~~~~~~~~~~~~~
233         })
    ~~~~~~~~~~
```
It can be easily fixed by putting the right types

Valentino

**Comment by bfabio** [comment]
Hello @valentinoavon,
@emilioSp pointed out to me that we use `yarn`, not `npm`, so a `yarn build` should do the trick.

Sorry for the confusion.

**Comment by bfabio** [comment]
@valentinoavon do you think we can close this one?

**Comment by valentinoavon** [comment]
I didn't try but it's ok to me!
