### ISSUE TITLE
Redis as a required dependency

### ISSUE THREAD

**Issue by CVarisco** [italia/spid-express#27]
Hi!

First of all, thank you so much for your support to the community, I really appreciate it!
I'm investigating to integrate SPID for a bunch of things and I'm looking for some information about this middleware before using it.

I was wondering about the reason why Redis (or a cache system in general) is required as a dependency.
From what I understood the usage of the cache is not strictly correlated to the authentication flow, is it correct?  
Could you tell why exists and why is useful for the process?

Thank you 🚀

**Comment by bfabio** [comment]
Thanks @CVarisco :heart: 

Redis is used to store the _state_ of the sessions, so it's instrumental to the whole authentication flow. Looking at the README it's probably misleading to mention caching there, I'm going to fix that.

Having said that, I think we need to abstract the state part and provide something more generic. Keeping the issue open!

**Comment by CVarisco** [comment]
Thank you @bfabio for your help and changes ❤️ 

Just to ask, Is there available a sort of flow chart to document the authentication flow for this library?
It would be awesome to have it to make more clear the state of the art when using `spid-express`.
Also because it would be great if `spid-express` or another `spid-X` will be used as a standalone microservice.

What do you think about it?

**Comment by peppelinux** [comment]
Ciao @CVarisco,

The authn flow is a quite common SAML2 use case with HTTP-REDIRECT/POST binding.
I suggest you to use a saml tracer as a browser extension (see it for firefox and chrome) to keep an eye on the SAML2 objects beign exchanged by your browser and the SAML2 entities, SP first and IDP then.

that's something that will give you more akcnowledgement on the SAMLRequest passed though HTTP-REDIRECT (GET args) and HTTP-POST (POST) without worrying too much about the encoding system that the two bindings use (inflate in http-redirect).

Let us know

**Comment by CVarisco** [comment]
Hi @peppelinux 

thanks to clarifying what is all about 😃 I'll try to see what happen with the browser extension as you suggest to understand more about it!

What I do not understand is how can I use this library as an external "service" for my application? That's why I'm asking about Redis.
Because from what I understood (but 99% I'm wrong), Redis is used to store the information needed for the business logic (authorization part).
So, I thought I can use Redis as a "bridge" between these two services.
I just attach my general idea on what I would like to achieve, maybe can help you or someone else 😃

<img width="983" alt="Screenshot 2021-01-20 at 10 32 16" src="https://user-images.githubusercontent.com/7335613/105155421-df5ac300-5b0a-11eb-994d-14be720ff16e.png">


PS: I know that you're not responsible for issues like this, so, don't worry if you can't or won't to respond ❤️  I appreciate in any case your contribution to the community!

**Comment by peppelinux** [comment]
You're right, I'm not responsible for that but at the same time I'm curious about your question, so I'll tell you how I adopt Redis, in my use cases. 

I use Redis when I have a distributed asset, many systems that relys on a single shared storage (active user sessions, pending transactions and things) with a TTL strategy. You can scale on many frontends and backends thanks to Redis, that keeps all the useful informations available to your entities. 

Diggin in the code:
https://github.com/italia/spid-express/search?q=Redis

as we can see Redis it's only a Cache provider, that's all, common use case after all

**Comment by peppelinux** [comment]
Feel free to close this issue and then moving to a specialized Topic

**Comment by CVarisco** [comment]
Thanks @peppelinux !
Probably I used not the right words to ask you 😀
I used Redis as you mention in other use cases and that's fine, I just wondering how can I use Redis for my specific purpose with SPID😀

I think could be useful for other people this issue. I'll close it to remove it from the open issue list!

Thank you again, super helpful!
