### ISSUE TITLE
Cannot run example application

### ISSUE THREAD

**Issue by vincenzocorso** [italia/spid-express#31]
Hi,
I tried to start the example application.

From the root folder I typed:
`docker-compose up`

The application starts, but if I go to [http://localhost:3000/login?entityID=posteid_testenv2](http://localhost:3000/login?entityID=posteid_testenv2), I get this error:
`"error": "Missing idpIssuer inside configuration"`

Instead if I go to [https://localhost:3000/login?entityID=posteid_testenv2](https://localhost:3000/login?entityID=posteid_testenv2) (using https) the page doesn't load and I get this error:
`Connessione sicura non riuscita
Si è verificato un errore durante la connessione a localhost:3000. SSL ha ricevuto un pacchetto che eccede la dimensione massima consentita.
Codice di errore: SSL_ERROR_RX_RECORD_TOO_LONG`

**Comment by bfabio** [comment]
Hello @vincenzocorso, there's a misunderstanding about the `entityID` format: `entityID=xx_testenv2` is supposed to be used verbatim (ie, the `xx` is not to be replaced by something else).

In production you'd use `https://example.com/login?entityID=posteid`.

Maybe we can improve the documentation there.
